### ISSUE TITLE
error in script

### ISSUE THREAD

**Issue by Itai-Nelken** [slashtechno/PiStaticIP#4]
<pre>If you are running with sudo press control+c
If you are running without press enter
Are you using WiFi(Press 1) or Ethernet (Press 2)2

default via 192.168.1.1 dev eth0 proto dhcp src 192.168.1.49 metric 202 mtu 1500 
192.168.1.0/24 dev eth0 proto dhcp scope link src 192.168.1.49 metric 202 mtu 1500 
Traceback (most recent call last):
  File &quot;staticIP&quot;, line 14, in &lt;module&gt;
    str(result)
NameError: name &apos;result&apos; is not defined
</pre>

**Comment by slashtechno** [comment]
Fixed in #5. Does it work now?

**Comment by Itai-Nelken** [comment]
so far it works.
